# Docker Web Dev Env

networks:
  web-dev-network:

services:
  mysql8.2:
    image: mysql:8.2
    container_name: mysql8.2
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    tty: true
    volumes:
      - ./mysql/8.2:/var/lib/mysql:delegated
      - ./mysql_init:/docker-entrypoint-initdb.d:cached
    ports:
      - "3308:3306"
    environment:
      # MYSQL_DATABASE: homestead
      # MYSQL_USER: homestead
      # MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql8.2
    networks:
      - web-dev-network

  mysql8.0:
    image: mysql:8.0
    container_name: mysql8.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    tty: true
    volumes:
      - ./mysql/8.0:/var/lib/mysql:delegated
      - ./mysql_init:/docker-entrypoint-initdb.d:cached
    ports:
      - "3307:3306"
    environment:
      # MYSQL_DATABASE: homestead
      # MYSQL_USER: homestead
      # MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql8.0
    networks:
      - web-dev-network

  mysql5.7:
    image: mysql:5.7
    container_name: mysql5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    tty: true
    volumes:
      - ./mysql/5.7:/var/lib/mysql:delegated
      - ./mysql_init:/docker-entrypoint-initdb.d:cached
    ports:
      - "3306:3306"
    environment:
      # MYSQL_DATABASE: homestead
      # MYSQL_USER: homestead
      # MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql5.7
    networks:
      - web-dev-network

  redis6:
    image: redis:6-alpine
    container_name: redis6
    restart: unless-stopped
    tty: true
    ports:
      - "6379:6379"
    networks:
      - web-dev-network

  php7.4:
    user: ${USER_ID:-0}:${GROUP_ID:-0}
    build:
      context: .
      dockerfile: php7.4.dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    image: "php7.4:dev"
    container_name: "php7.4_dev"
    restart: unless-stopped
    volumes:
      - ./web:/var/www/html:delegated
      - ./log/php7.4:/var/log/php:delegated
      - ./php/php7.4/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:cached
      - ./php/php7.4/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini:cached
      - ./php/php7.4/conf.d/docker-php.ini:/usr/local/etc/php/conf.d/docker-php.ini:cached
    depends_on:
      - mysql8.2
      - mysql8.0
      - mysql5.7
      - redis6
    networks:
      - web-dev-network

  php8.1:
    user: ${USER_ID:-0}:${GROUP_ID:-0}
    build:
      context: .
      dockerfile: php8.1.dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    image: "php8.1:dev"
    container_name: "php8.1_dev"
    restart: unless-stopped
    volumes:
      - ./web:/var/www/html:delegated
      - ./log/php8.1:/var/log/php:delegated
      - ./php/php8.1/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:cached
      - ./php/php8.1/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini:cached
      - ./php/php8.1/conf.d/docker-php.ini:/usr/local/etc/php/conf.d/docker-php.ini:cached
    depends_on:
      - mysql8.2
      - mysql8.0
      - mysql5.7
      - redis6
    networks:
      - web-dev-network
    extra_hosts:
      - wp-cb.local:192.168.100.10

  php8.3:
    user: ${USER_ID:-0}:${GROUP_ID:-0}
    build:
      context: .
      dockerfile: php8.3.dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    image: "php8.3:dev"
    container_name: "php8.3_dev"
    restart: unless-stopped
    volumes:
      - ./web:/var/www/html:delegated
      - ./log/php8.3:/var/log/php:delegated
      - ./php/php8.3/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:cached
      - ./php/php8.3/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini:cached
      - ./php/php8.3/conf.d/docker-php.ini:/usr/local/etc/php/conf.d/docker-php.ini:cached
    depends_on:
      - mysql8.2
      - mysql8.0
      - mysql5.7
      - redis6
    networks:
      - web-dev-network

  nginx:
    image: nginx:stable-alpine
    container_name: web_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./web:/var/www/html:delegated
      - ./log:/var/log/nginx:delegated
      - ./nginx/conf.d:/etc/nginx/conf.d:cached
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:cached
    depends_on:
      - php7.4
      - php8.1
      - php8.3
    networks:
      web-dev-network:
        aliases:
          - wp-cb.local
