#!/bin/bash
# export SYS_PHP_VER
#docker-compose run --rm php myproject/artisan $@
CMD=$@
WPATH=$(pwd)
PROJ="${WPATH##*/}"

if [ -f ".env" ]; then
    source ".env"
    echo "SYS_PHP_VER=${SYS_PHP_VER}"
fi

CONTAIN_ID=""
if [ "$SYS_PHP_VER" = "8.1" ]; then
    CONTAIN_ID=$(docker ps -aqf "name=^php8.1_dev$")
else
    CONTAIN_ID=$(docker ps -aqf "name=^php7.4_dev$")
fi

if [ "$CONTAIN_ID" = "" ]; then
    echo "Docker container is not exist or running."
else
    docker exec -w "/var/www/html/$PROJ" --user "$(id -u):$(id -g)" -it $CONTAIN_ID php artisan $CMD
fi